/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, type ResultProblem } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /echo
 */
export interface EchoRequestBuilder extends BaseRequestBuilder<EchoRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<EchoRequestBuilderGetQueryParameters> | undefined) : Promise<string | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<EchoRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface EchoRequestBuilderGetQueryParameters {
    message?: string;
}
/**
 * Uri template for the request builder.
 */
export const EchoRequestBuilderUriTemplate = "{+baseurl}/echo{?message*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const EchoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EchoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "string",
    },
};
/* tslint:enable */
/* eslint-enable */
