/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FrontendAuthConfig}
 */
// @ts-ignore
export function createFrontendAuthConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFrontendAuthConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Message}
 */
// @ts-ignore
export function createMessageFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMessage;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MessageRequest}
 */
// @ts-ignore
export function createMessageRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMessageRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PageOfMessage}
 */
// @ts-ignore
export function createPageOfMessageFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPageOfMessage;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Pagination}
 */
// @ts-ignore
export function createPaginationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPagination;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultProblem}
 */
// @ts-ignore
export function createResultProblemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultProblem;
}
/**
 * The deserialization information for the current model
 * @param FrontendAuthConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFrontendAuthConfig(frontendAuthConfig: Partial<FrontendAuthConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "authority": n => { frontendAuthConfig.authority = n.getStringValue(); },
        "clientId": n => { frontendAuthConfig.clientId = n.getStringValue(); },
        "scopes": n => { frontendAuthConfig.scopes = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Message The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMessage(message: Partial<Message> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { message.id = n.getGuidValue(); },
        "text": n => { message.text = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MessageRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMessageRequest(messageRequest: Partial<MessageRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "text": n => { messageRequest.text = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PageOfMessage The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPageOfMessage(pageOfMessage: Partial<PageOfMessage> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "hasNextPage": n => { pageOfMessage.hasNextPage = n.getBooleanValue(); },
        "items": n => { pageOfMessage.items = n.getCollectionOfObjectValues<Message>(createMessageFromDiscriminatorValue); },
        "next": n => { pageOfMessage.next = n.getObjectValue<Pagination>(createPaginationFromDiscriminatorValue); },
        "pageNumber": n => { pageOfMessage.pageNumber = n.getNumberValue(); },
        "pageSize": n => { pageOfMessage.pageSize = n.getNumberValue(); },
        "totalCount": n => { pageOfMessage.totalCount = n.getNumberValue(); },
        "totalPages": n => { pageOfMessage.totalPages = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Pagination The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPagination(pagination: Partial<Pagination> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "offset": n => { pagination.offset = n.getNumberValue(); },
        "page": n => { pagination.page = n.getNumberValue(); },
        "pageSize": n => { pagination.pageSize = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultProblem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultProblem(resultProblem: Partial<ResultProblem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exceptionSummary": n => { resultProblem.exceptionSummary = n.getStringValue(); },
        "isRetryable": n => { resultProblem.isRetryable = n.getBooleanValue(); },
        "message": n => { resultProblem.messageEscaped = n.getStringValue(); },
        "severity": n => { resultProblem.severity = n.getNumberValue(); },
        "source": n => { resultProblem.source = n.getStringValue(); },
        "tags": n => { resultProblem.tags = n.getCollectionOfPrimitiveValues<string>("string"); },
    }
}
export interface FrontendAuthConfig extends AdditionalDataHolder, Parsable {
    /**
     * The authority property
     */
    authority?: string | null;
    /**
     * The clientId property
     */
    clientId?: string | null;
    /**
     * The scopes property
     */
    scopes?: string | null;
}
export interface Message extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The text property
     */
    text?: string | null;
}
export interface MessageRequest extends AdditionalDataHolder, Parsable {
    /**
     * The text property
     */
    text?: string | null;
}
export interface PageOfMessage extends AdditionalDataHolder, Parsable {
    /**
     * The hasNextPage property
     */
    hasNextPage?: boolean | null;
    /**
     * The items property
     */
    items?: Message[] | null;
    /**
     * The next property
     */
    next?: Pagination | null;
    /**
     * The pageNumber property
     */
    pageNumber?: number | null;
    /**
     * The pageSize property
     */
    pageSize?: number | null;
    /**
     * The totalCount property
     */
    totalCount?: number | null;
    /**
     * The totalPages property
     */
    totalPages?: number | null;
}
export interface Pagination extends AdditionalDataHolder, Parsable {
    /**
     * The offset property
     */
    offset?: number | null;
    /**
     * The page property
     */
    page?: number | null;
    /**
     * The pageSize property
     */
    pageSize?: number | null;
}
export interface ResultProblem extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The exceptionSummary property
     */
    exceptionSummary?: string | null;
    /**
     * The isRetryable property
     */
    isRetryable?: boolean | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The severity property
     */
    severity?: number | null;
    /**
     * The source property
     */
    source?: string | null;
    /**
     * The tags property
     */
    tags?: string[] | null;
}
/**
 * Serializes information the current object
 * @param FrontendAuthConfig The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFrontendAuthConfig(writer: SerializationWriter, frontendAuthConfig: Partial<FrontendAuthConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!frontendAuthConfig || isSerializingDerivedType) { return; }
    writer.writeStringValue("authority", frontendAuthConfig.authority);
    writer.writeStringValue("clientId", frontendAuthConfig.clientId);
    writer.writeStringValue("scopes", frontendAuthConfig.scopes);
    writer.writeAdditionalData(frontendAuthConfig.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Message The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMessage(writer: SerializationWriter, message: Partial<Message> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!message || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", message.id);
    writer.writeStringValue("text", message.text);
    writer.writeAdditionalData(message.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MessageRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMessageRequest(writer: SerializationWriter, messageRequest: Partial<MessageRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!messageRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("text", messageRequest.text);
    writer.writeAdditionalData(messageRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PageOfMessage The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePageOfMessage(writer: SerializationWriter, pageOfMessage: Partial<PageOfMessage> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pageOfMessage || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("hasNextPage", pageOfMessage.hasNextPage);
    writer.writeCollectionOfObjectValues<Message>("items", pageOfMessage.items, serializeMessage);
    writer.writeObjectValue<Pagination>("next", pageOfMessage.next, serializePagination);
    writer.writeNumberValue("pageNumber", pageOfMessage.pageNumber);
    writer.writeNumberValue("pageSize", pageOfMessage.pageSize);
    writer.writeNumberValue("totalCount", pageOfMessage.totalCount);
    writer.writeNumberValue("totalPages", pageOfMessage.totalPages);
    writer.writeAdditionalData(pageOfMessage.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Pagination The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePagination(writer: SerializationWriter, pagination: Partial<Pagination> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pagination || isSerializingDerivedType) { return; }
    writer.writeNumberValue("offset", pagination.offset);
    writer.writeNumberValue("page", pagination.page);
    writer.writeNumberValue("pageSize", pagination.pageSize);
    writer.writeAdditionalData(pagination.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultProblem The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultProblem(writer: SerializationWriter, resultProblem: Partial<ResultProblem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultProblem || isSerializingDerivedType) { return; }
    writer.writeStringValue("exceptionSummary", resultProblem.exceptionSummary);
    writer.writeBooleanValue("isRetryable", resultProblem.isRetryable);
    writer.writeStringValue("message", resultProblem.messageEscaped);
    writer.writeNumberValue("severity", resultProblem.severity);
    writer.writeStringValue("source", resultProblem.source);
    writer.writeCollectionOfPrimitiveValues<string>("tags", resultProblem.tags);
    writer.writeAdditionalData(resultProblem.additionalData);
}
/* tslint:enable */
/* eslint-enable */
