replicaCount: 1

image:
  repository: olve-template-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  Host: "0.0.0.0"
  Port: "5000"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
