/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFrontendAuthConfigFromDiscriminatorValue, type FrontendAuthConfig } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth-config
 */
export interface AuthConfigRequestBuilder extends BaseRequestBuilder<AuthConfigRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FrontendAuthConfig>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FrontendAuthConfig | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AuthConfigRequestBuilderUriTemplate = "{+baseurl}/api/auth-config";
/**
 * Metadata for all the requests in the request builder.
 */
export const AuthConfigRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AuthConfigRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFrontendAuthConfigFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
